name: actors
description: Actors Model library for Dart. It is a thin wrapper around Dart's `Isolate` that makes them much easier to use.
version: 0.7.0-nullsafety.0
homepage: https://github.com/renatoathaydes/actors

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.9
