name: actors
description: Actors Model library for Dart. It is a thin wrapper around Dart's `Isolate` that makes them much easier to use.
version: 0.7.0-nullsafety
homepage: https://github.com/renatoathaydes/actors

environment:
  sdk: ">=2.11.0-213.5.beta <2.12.0"

dependencies:

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
