name: actors
description: Actors Model library for Dart. It is a thin wrapper around Dart's `Isolate` that makes them much easier to use.
version: 0.9.0
homepage: https://github.com/renatoathaydes/actors

environment:
  sdk: ^3.0.0

dependencies:

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  path: ^1.8.3
  benchmark_harness: any
  conveniently: ^1.1.0
  collection: ^1.18.0

# 'web' will only be supported if/when web_workers are implemented
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
