name: actors
description: Actors Model library for Dart. It is a thin wrapper around Dart's `Isolate` that makes them much easier to use.
version: 0.8.1
homepage: https://github.com/renatoathaydes/actors

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5

